#!/bin/bash
#change to take keyboard input
password="12qw!@QW"
echo Our password is $password
echo "" > passwdchanges.txt

#Lock Root account
usermod -L root

#Users with  uids > 1000
for usr in $(awk -F: '$3 >= 1000 {print $1}' /etc/passwd | sort -r); do
          echo "Assigning $usr secure password."
          echo "$usr:$password" | sudo chpasswd
          echo "$usr" >> passwdchanges.txt
done

#Service Accountss
for usr in $(awk -F: '$3 < 1000 {print $1}' /etc/passwd | sort -r); do
          echo "Assigning $usr secure password."
          echo "$usr:$password" | sudo chpasswd
          echo "$usr" >> passwdchanges.txt
done
